/* dialogs.c generated by valac 0.48.8, the Vala compiler
 * generated from dialogs.vala, do not modify */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>

#define TYPE_MY_CONTAINER (my_container_get_type ())
#define MY_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MY_CONTAINER, MyContainer))
#define MY_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MY_CONTAINER, MyContainerClass))
#define IS_MY_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MY_CONTAINER))
#define IS_MY_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MY_CONTAINER))
#define MY_CONTAINER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MY_CONTAINER, MyContainerClass))

typedef struct _MyContainer MyContainer;
typedef struct _MyContainerClass MyContainerClass;
typedef struct _MyContainerPrivate MyContainerPrivate;
enum  {
	MY_CONTAINER_0_PROPERTY,
	MY_CONTAINER_NUM_PROPERTIES
};
static GParamSpec* my_container_properties[MY_CONTAINER_NUM_PROPERTIES];

#define TYPE_APP_DIALOG (app_dialog_get_type ())
#define APP_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_APP_DIALOG, AppDialog))
#define APP_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_APP_DIALOG, AppDialogClass))
#define IS_APP_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_APP_DIALOG))
#define IS_APP_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_APP_DIALOG))
#define APP_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_APP_DIALOG, AppDialogClass))

typedef struct _AppDialog AppDialog;
typedef struct _AppDialogClass AppDialogClass;
typedef struct _AppDialogPrivate AppDialogPrivate;
enum  {
	APP_DIALOG_0_PROPERTY,
	APP_DIALOG_NUM_PROPERTIES
};
static GParamSpec* app_dialog_properties[APP_DIALOG_NUM_PROPERTIES];

struct _MyContainer {
	GtkContainer parent_instance;
	MyContainerPrivate * priv;
};

struct _MyContainerClass {
	GtkContainerClass parent_class;
};

struct _AppDialog {
	GtkDialog parent_instance;
	AppDialogPrivate * priv;
};

struct _AppDialogClass {
	GtkDialogClass parent_class;
};

static gpointer my_container_parent_class = NULL;
static gpointer app_dialog_parent_class = NULL;

GType my_container_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (MyContainer, g_object_unref)
MyContainer* my_container_new (void);
MyContainer* my_container_construct (GType object_type);
static GType my_container_get_type_once (void);
GType app_dialog_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (AppDialog, g_object_unref)
AppDialog* app_dialog_new (void);
AppDialog* app_dialog_construct (GType object_type);
AppDialog* app_dialog_new_with_buttons (const gchar* title,
                                        GtkWindow* parent,
                                        gint flag1,
                                        const gchar* key_label,
                                        gint type,
                                        const gchar* end);
AppDialog* app_dialog_construct_with_buttons (GType object_type,
                                              const gchar* title,
                                              GtkWindow* parent,
                                              gint flag1,
                                              const gchar* key_label,
                                              gint type,
                                              const gchar* end);
static GType app_dialog_get_type_once (void);

MyContainer*
my_container_construct (GType object_type)
{
	MyContainer * self = NULL;
#line 3 "../src/dialogs.vala"
	self = (MyContainer*) g_object_new (object_type, NULL);
#line 3 "../src/dialogs.vala"
	return self;
#line 96 "dialogs.c"
}

MyContainer*
my_container_new (void)
{
#line 3 "../src/dialogs.vala"
	return my_container_construct (TYPE_MY_CONTAINER);
#line 104 "dialogs.c"
}

static void
my_container_class_init (MyContainerClass * klass,
                         gpointer klass_data)
{
#line 3 "../src/dialogs.vala"
	my_container_parent_class = g_type_class_peek_parent (klass);
#line 113 "dialogs.c"
}

static void
my_container_instance_init (MyContainer * self,
                            gpointer klass)
{
}

static GType
my_container_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (MyContainerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) my_container_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MyContainer), 0, (GInstanceInitFunc) my_container_instance_init, NULL };
	GType my_container_type_id;
	my_container_type_id = g_type_register_static (gtk_container_get_type (), "MyContainer", &g_define_type_info, 0);
	return my_container_type_id;
}

GType
my_container_get_type (void)
{
	static volatile gsize my_container_type_id__volatile = 0;
	if (g_once_init_enter (&my_container_type_id__volatile)) {
		GType my_container_type_id;
		my_container_type_id = my_container_get_type_once ();
		g_once_init_leave (&my_container_type_id__volatile, my_container_type_id);
	}
	return my_container_type_id__volatile;
}

AppDialog*
app_dialog_construct (GType object_type)
{
	AppDialog * self = NULL;
#line 7 "../src/dialogs.vala"
	self = (AppDialog*) g_object_new (object_type, NULL);
#line 7 "../src/dialogs.vala"
	return self;
#line 151 "dialogs.c"
}

AppDialog*
app_dialog_new (void)
{
#line 7 "../src/dialogs.vala"
	return app_dialog_construct (TYPE_APP_DIALOG);
#line 159 "dialogs.c"
}

AppDialog*
app_dialog_construct_with_buttons (GType object_type,
                                   const gchar* title,
                                   GtkWindow* parent,
                                   gint flag1,
                                   const gchar* key_label,
                                   gint type,
                                   const gchar* end)
{
	AppDialog * self = NULL;
#line 8 "../src/dialogs.vala"
	g_return_val_if_fail (title != NULL, NULL);
#line 8 "../src/dialogs.vala"
	g_return_val_if_fail (parent != NULL, NULL);
#line 8 "../src/dialogs.vala"
	g_return_val_if_fail (key_label != NULL, NULL);
#line 8 "../src/dialogs.vala"
	g_return_val_if_fail (end != NULL, NULL);
#line 8 "../src/dialogs.vala"
	self = (AppDialog*) g_object_new (object_type, NULL);
#line 8 "../src/dialogs.vala"
	return self;
#line 184 "dialogs.c"
}

AppDialog*
app_dialog_new_with_buttons (const gchar* title,
                             GtkWindow* parent,
                             gint flag1,
                             const gchar* key_label,
                             gint type,
                             const gchar* end)
{
#line 8 "../src/dialogs.vala"
	return app_dialog_construct_with_buttons (TYPE_APP_DIALOG, title, parent, flag1, key_label, type, end);
#line 197 "dialogs.c"
}

static void
app_dialog_class_init (AppDialogClass * klass,
                       gpointer klass_data)
{
#line 6 "../src/dialogs.vala"
	app_dialog_parent_class = g_type_class_peek_parent (klass);
#line 206 "dialogs.c"
}

static void
app_dialog_instance_init (AppDialog * self,
                          gpointer klass)
{
}

static GType
app_dialog_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (AppDialogClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) app_dialog_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AppDialog), 0, (GInstanceInitFunc) app_dialog_instance_init, NULL };
	GType app_dialog_type_id;
	app_dialog_type_id = g_type_register_static (gtk_dialog_get_type (), "AppDialog", &g_define_type_info, 0);
	return app_dialog_type_id;
}

GType
app_dialog_get_type (void)
{
	static volatile gsize app_dialog_type_id__volatile = 0;
	if (g_once_init_enter (&app_dialog_type_id__volatile)) {
		GType app_dialog_type_id;
		app_dialog_type_id = app_dialog_get_type_once ();
		g_once_init_leave (&app_dialog_type_id__volatile, app_dialog_type_id);
	}
	return app_dialog_type_id__volatile;
}

