/* main_gui.c generated by valac 0.48.8, the Vala compiler
 * generated from main_gui.vala, do not modify */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <glib.h>

#define TYPE_SDE_TOOL (sde_tool_get_type ())
#define SDE_TOOL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SDE_TOOL, SDETool))
#define SDE_TOOL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SDE_TOOL, SDEToolClass))
#define IS_SDE_TOOL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SDE_TOOL))
#define IS_SDE_TOOL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SDE_TOOL))
#define SDE_TOOL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SDE_TOOL, SDEToolClass))

typedef struct _SDETool SDETool;
typedef struct _SDEToolClass SDEToolClass;
typedef struct _SDEToolPrivate SDEToolPrivate;
enum  {
	SDE_TOOL_0_PROPERTY,
	SDE_TOOL_NUM_PROPERTIES
};
static GParamSpec* sde_tool_properties[SDE_TOOL_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _SDETool {
	GtkWindow parent_instance;
	SDEToolPrivate * priv;
};

struct _SDEToolClass {
	GtkWindowClass parent_class;
};

static gpointer sde_tool_parent_class = NULL;

GType sde_tool_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (SDETool, g_object_unref)
SDETool* sde_tool_new (void);
SDETool* sde_tool_construct (GType object_type);
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender,
                                        gpointer self);
static void sde_tool_on_clicked_app_exit (SDETool* self,
                                   GtkButton* button);
static void _sde_tool_on_clicked_app_exit_gtk_button_clicked (GtkButton* _sender,
                                                       gpointer self);
static void sde_tool_on_clicked_app_info (SDETool* self,
                                   GtkButton* button);
static void _sde_tool_on_clicked_app_info_gtk_button_clicked (GtkButton* _sender,
                                                       gpointer self);
static void _gtk_widget_destroy_gtk_dialog_response (GtkDialog* _sender,
                                              gint response_id,
                                              gpointer self);
static GType sde_tool_get_type_once (void);

static void
_gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender,
                                   gpointer self)
{
#line 6 "../src/main_gui.vala"
	gtk_main_quit ();
#line 62 "main_gui.c"
}

static void
_sde_tool_on_clicked_app_exit_gtk_button_clicked (GtkButton* _sender,
                                                  gpointer self)
{
#line 28 "../src/main_gui.vala"
	sde_tool_on_clicked_app_exit ((SDETool*) self, _sender);
#line 71 "main_gui.c"
}

static void
_sde_tool_on_clicked_app_info_gtk_button_clicked (GtkButton* _sender,
                                                  gpointer self)
{
#line 33 "../src/main_gui.vala"
	sde_tool_on_clicked_app_info ((SDETool*) self, _sender);
#line 80 "main_gui.c"
}

SDETool*
sde_tool_construct (GType object_type)
{
	SDETool * self = NULL;
	GtkBox* box = NULL;
	GtkBox* _tmp0_;
	GtkBox* mbar = NULL;
	GtkBox* _tmp1_;
	GtkButton* but_config = NULL;
	GtkButton* _tmp2_;
	GtkButton* but_add = NULL;
	GtkButton* _tmp3_;
	GtkButton* but_exit = NULL;
	GtkButton* _tmp4_;
	GtkButton* but_info = NULL;
	GtkButton* _tmp5_;
	GtkNotebook* notebook = NULL;
	GtkNotebook* _tmp6_;
	GtkScrolledWindow* page1 = NULL;
	GtkScrolledWindow* _tmp7_;
	GtkLabel* _tmp8_;
	GtkLabel* _tmp9_;
#line 5 "../src/main_gui.vala"
	self = (SDETool*) g_object_new (object_type, NULL);
#line 6 "../src/main_gui.vala"
	g_signal_connect ((GtkWidget*) self, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
#line 7 "../src/main_gui.vala"
	gtk_window_set_title ((GtkWindow*) self, "SDE Tool");
#line 8 "../src/main_gui.vala"
	gtk_window_set_default_size ((GtkWindow*) self, 800, 400);
#line 9 "../src/main_gui.vala"
	gtk_container_set_border_width ((GtkContainer*) self, (guint) 1);
#line 11 "../src/main_gui.vala"
	_tmp0_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
#line 11 "../src/main_gui.vala"
	g_object_ref_sink (_tmp0_);
#line 11 "../src/main_gui.vala"
	box = _tmp0_;
#line 12 "../src/main_gui.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) box);
#line 15 "../src/main_gui.vala"
	_tmp1_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0);
#line 15 "../src/main_gui.vala"
	g_object_ref_sink (_tmp1_);
#line 15 "../src/main_gui.vala"
	mbar = _tmp1_;
#line 16 "../src/main_gui.vala"
	gtk_box_pack_start (box, (GtkWidget*) mbar, FALSE, TRUE, (guint) 0);
#line 19 "../src/main_gui.vala"
	_tmp2_ = (GtkButton*) gtk_button_new_from_icon_name ("emblem-system", (GtkIconSize) GTK_ICON_SIZE_BUTTON);
#line 19 "../src/main_gui.vala"
	g_object_ref_sink (_tmp2_);
#line 19 "../src/main_gui.vala"
	but_config = _tmp2_;
#line 20 "../src/main_gui.vala"
	gtk_box_pack_start (mbar, (GtkWidget*) but_config, FALSE, TRUE, (guint) 0);
#line 23 "../src/main_gui.vala"
	_tmp3_ = (GtkButton*) gtk_button_new_from_icon_name ("list-add", (GtkIconSize) GTK_ICON_SIZE_BUTTON);
#line 23 "../src/main_gui.vala"
	g_object_ref_sink (_tmp3_);
#line 23 "../src/main_gui.vala"
	but_add = _tmp3_;
#line 24 "../src/main_gui.vala"
	gtk_box_pack_start (mbar, (GtkWidget*) but_add, FALSE, TRUE, (guint) 0);
#line 27 "../src/main_gui.vala"
	_tmp4_ = (GtkButton*) gtk_button_new_from_icon_name ("application-exit", (GtkIconSize) GTK_ICON_SIZE_BUTTON);
#line 27 "../src/main_gui.vala"
	g_object_ref_sink (_tmp4_);
#line 27 "../src/main_gui.vala"
	but_exit = _tmp4_;
#line 28 "../src/main_gui.vala"
	g_signal_connect_object (but_exit, "clicked", (GCallback) _sde_tool_on_clicked_app_exit_gtk_button_clicked, self, 0);
#line 29 "../src/main_gui.vala"
	gtk_box_pack_end (mbar, (GtkWidget*) but_exit, FALSE, TRUE, (guint) 0);
#line 32 "../src/main_gui.vala"
	_tmp5_ = (GtkButton*) gtk_button_new_from_icon_name ("dialog-information", (GtkIconSize) GTK_ICON_SIZE_BUTTON);
#line 32 "../src/main_gui.vala"
	g_object_ref_sink (_tmp5_);
#line 32 "../src/main_gui.vala"
	but_info = _tmp5_;
#line 33 "../src/main_gui.vala"
	g_signal_connect_object (but_info, "clicked", (GCallback) _sde_tool_on_clicked_app_info_gtk_button_clicked, self, 0);
#line 34 "../src/main_gui.vala"
	gtk_box_pack_end (mbar, (GtkWidget*) but_info, FALSE, TRUE, (guint) 0);
#line 37 "../src/main_gui.vala"
	_tmp6_ = (GtkNotebook*) gtk_notebook_new ();
#line 37 "../src/main_gui.vala"
	g_object_ref_sink (_tmp6_);
#line 37 "../src/main_gui.vala"
	notebook = _tmp6_;
#line 38 "../src/main_gui.vala"
	gtk_box_pack_start (box, (GtkWidget*) notebook, TRUE, TRUE, (guint) 0);
#line 41 "../src/main_gui.vala"
	_tmp7_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
#line 41 "../src/main_gui.vala"
	g_object_ref_sink (_tmp7_);
#line 41 "../src/main_gui.vala"
	page1 = _tmp7_;
#line 42 "../src/main_gui.vala"
	gtk_scrolled_window_set_policy (page1, GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
#line 47 "../src/main_gui.vala"
	_tmp8_ = (GtkLabel*) gtk_label_new ("Main");
#line 47 "../src/main_gui.vala"
	g_object_ref_sink (_tmp8_);
#line 47 "../src/main_gui.vala"
	_tmp9_ = _tmp8_;
#line 47 "../src/main_gui.vala"
	gtk_notebook_append_page (notebook, (GtkWidget*) page1, (GtkWidget*) _tmp9_);
#line 47 "../src/main_gui.vala"
	_g_object_unref0 (_tmp9_);
#line 5 "../src/main_gui.vala"
	_g_object_unref0 (page1);
#line 5 "../src/main_gui.vala"
	_g_object_unref0 (notebook);
#line 5 "../src/main_gui.vala"
	_g_object_unref0 (but_info);
#line 5 "../src/main_gui.vala"
	_g_object_unref0 (but_exit);
#line 5 "../src/main_gui.vala"
	_g_object_unref0 (but_add);
#line 5 "../src/main_gui.vala"
	_g_object_unref0 (but_config);
#line 5 "../src/main_gui.vala"
	_g_object_unref0 (mbar);
#line 5 "../src/main_gui.vala"
	_g_object_unref0 (box);
#line 5 "../src/main_gui.vala"
	return self;
#line 211 "main_gui.c"
}

SDETool*
sde_tool_new (void)
{
#line 5 "../src/main_gui.vala"
	return sde_tool_construct (TYPE_SDE_TOOL);
#line 219 "main_gui.c"
}

static void
sde_tool_on_clicked_app_exit (SDETool* self,
                              GtkButton* button)
{
#line 51 "../src/main_gui.vala"
	g_return_if_fail (self != NULL);
#line 51 "../src/main_gui.vala"
	g_return_if_fail (button != NULL);
#line 52 "../src/main_gui.vala"
	gtk_main_quit ();
#line 232 "main_gui.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 62 "../src/main_gui.vala"
	return self ? g_object_ref (self) : NULL;
#line 240 "main_gui.c"
}

static void
_gtk_widget_destroy_gtk_dialog_response (GtkDialog* _sender,
                                         gint response_id,
                                         gpointer self)
{
#line 76 "../src/main_gui.vala"
	gtk_widget_destroy ((GtkWidget*) self);
#line 250 "main_gui.c"
}

static void
sde_tool_on_clicked_app_info (SDETool* self,
                              GtkButton* button)
{
	GtkDialog* dialog = NULL;
	GtkDialog* _tmp0_;
	GtkBox* content = NULL;
	GtkBox* _tmp1_;
	GtkBox* _tmp2_;
	GtkBox* box = NULL;
	GtkBox* _tmp3_;
	GtkLabel* lab1 = NULL;
	GtkLabel* _tmp4_;
	GtkLabel* lab2 = NULL;
	GtkLabel* _tmp5_;
	GtkLabel* lab3 = NULL;
	GtkLabel* _tmp6_;
#line 56 "../src/main_gui.vala"
	g_return_if_fail (self != NULL);
#line 56 "../src/main_gui.vala"
	g_return_if_fail (button != NULL);
#line 57 "../src/main_gui.vala"
	_tmp0_ = (GtkDialog*) gtk_dialog_new_with_buttons ("About", (GtkWindow*) self, GTK_DIALOG_MODAL, "_OK", GTK_RESPONSE_NONE, NULL, NULL);
#line 57 "../src/main_gui.vala"
	g_object_ref_sink (_tmp0_);
#line 57 "../src/main_gui.vala"
	dialog = _tmp0_;
#line 62 "../src/main_gui.vala"
	_tmp1_ = gtk_dialog_get_content_area (dialog);
#line 62 "../src/main_gui.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 62 "../src/main_gui.vala"
	content = _tmp2_;
#line 64 "../src/main_gui.vala"
	_tmp3_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
#line 64 "../src/main_gui.vala"
	g_object_ref_sink (_tmp3_);
#line 64 "../src/main_gui.vala"
	box = _tmp3_;
#line 65 "../src/main_gui.vala"
	gtk_container_add ((GtkContainer*) content, (GtkWidget*) box);
#line 67 "../src/main_gui.vala"
	_tmp4_ = (GtkLabel*) gtk_label_new ("SDE Tool");
#line 67 "../src/main_gui.vala"
	g_object_ref_sink (_tmp4_);
#line 67 "../src/main_gui.vala"
	lab1 = _tmp4_;
#line 68 "../src/main_gui.vala"
	gtk_box_pack_start (box, (GtkWidget*) lab1, TRUE, TRUE, (guint) 0);
#line 70 "../src/main_gui.vala"
	_tmp5_ = (GtkLabel*) gtk_label_new ("version 0.1");
#line 70 "../src/main_gui.vala"
	g_object_ref_sink (_tmp5_);
#line 70 "../src/main_gui.vala"
	lab2 = _tmp5_;
#line 71 "../src/main_gui.vala"
	gtk_box_pack_start (box, (GtkWidget*) lab2, TRUE, TRUE, (guint) 0);
#line 73 "../src/main_gui.vala"
	_tmp6_ = (GtkLabel*) gtk_label_new ("(C) 2020 Keiichi Takahashi");
#line 73 "../src/main_gui.vala"
	g_object_ref_sink (_tmp6_);
#line 73 "../src/main_gui.vala"
	lab3 = _tmp6_;
#line 74 "../src/main_gui.vala"
	gtk_box_pack_start (box, (GtkWidget*) lab3, TRUE, TRUE, (guint) 0);
#line 76 "../src/main_gui.vala"
	g_signal_connect_object (dialog, "response", (GCallback) _gtk_widget_destroy_gtk_dialog_response, (GtkWidget*) dialog, 0);
#line 77 "../src/main_gui.vala"
	gtk_widget_show_all ((GtkWidget*) dialog);
#line 56 "../src/main_gui.vala"
	_g_object_unref0 (lab3);
#line 56 "../src/main_gui.vala"
	_g_object_unref0 (lab2);
#line 56 "../src/main_gui.vala"
	_g_object_unref0 (lab1);
#line 56 "../src/main_gui.vala"
	_g_object_unref0 (box);
#line 56 "../src/main_gui.vala"
	_g_object_unref0 (content);
#line 56 "../src/main_gui.vala"
	_g_object_unref0 (dialog);
#line 334 "main_gui.c"
}

static void
sde_tool_class_init (SDEToolClass * klass,
                     gpointer klass_data)
{
#line 3 "../src/main_gui.vala"
	sde_tool_parent_class = g_type_class_peek_parent (klass);
#line 343 "main_gui.c"
}

static void
sde_tool_instance_init (SDETool * self,
                        gpointer klass)
{
}

static GType
sde_tool_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (SDEToolClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) sde_tool_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SDETool), 0, (GInstanceInitFunc) sde_tool_instance_init, NULL };
	GType sde_tool_type_id;
	sde_tool_type_id = g_type_register_static (gtk_window_get_type (), "SDETool", &g_define_type_info, 0);
	return sde_tool_type_id;
}

GType
sde_tool_get_type (void)
{
	static volatile gsize sde_tool_type_id__volatile = 0;
	if (g_once_init_enter (&sde_tool_type_id__volatile)) {
		GType sde_tool_type_id;
		sde_tool_type_id = sde_tool_get_type_once ();
		g_once_init_leave (&sde_tool_type_id__volatile, sde_tool_type_id);
	}
	return sde_tool_type_id__volatile;
}

