/* main.c generated by valac 0.48.8, the Vala compiler
 * generated from main.vala, do not modify */

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gtk/gtk.h>
#include <glib-object.h>

#define TYPE_SDE_TOOL (sde_tool_get_type ())
#define SDE_TOOL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SDE_TOOL, SDETool))
#define SDE_TOOL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SDE_TOOL, SDEToolClass))
#define IS_SDE_TOOL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SDE_TOOL))
#define IS_SDE_TOOL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SDE_TOOL))
#define SDE_TOOL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SDE_TOOL, SDEToolClass))

typedef struct _SDETool SDETool;
typedef struct _SDEToolClass SDEToolClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

gint _vala_main (gchar** args,
                 gint args_length1);
GType sde_tool_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (SDETool, g_object_unref)
SDETool* sde_tool_new (void);
SDETool* sde_tool_construct (GType object_type);

gint
_vala_main (gchar** args,
            gint args_length1)
{
	SDETool* app = NULL;
	SDETool* _tmp0_;
	gint result = 0;
#line 4 "../src/main.vala"
	gtk_init ((gint*) (&args_length1), &args);
#line 6 "../src/main.vala"
	_tmp0_ = sde_tool_new ();
#line 6 "../src/main.vala"
	g_object_ref_sink (_tmp0_);
#line 6 "../src/main.vala"
	app = _tmp0_;
#line 7 "../src/main.vala"
	gtk_widget_show_all ((GtkWidget*) app);
#line 8 "../src/main.vala"
	gtk_main ();
#line 9 "../src/main.vala"
	result = 0;
#line 9 "../src/main.vala"
	_g_object_unref0 (app);
#line 9 "../src/main.vala"
	return result;
#line 54 "main.c"
}

int
main (int argc,
      char ** argv)
{
#line 3 "../src/main.vala"
	return _vala_main (argv, argc);
#line 63 "main.c"
}

